//! Rust-owned component and command contracts. Only immutable DTO bytes cross runtimes.
pub use crate::protocol::MAX_NATIVE_CALL_BYTES;
pub use serde;
pub use serde::{Deserialize, Serialize};
pub use ts_rs;
pub use ts_rs::TS;

/// A registered byte-only command dispatcher. The host awaits its replies off
/// foreground and applies completed replies on GPUI foreground. Dispatchers
/// generated by [`ModuleDefinition`] execute commands on their owned Tokio runtime.
pub trait NativeModule: Send + Sync {
    fn module_id(&self) -> [u8; 16];
    fn module_digest(&self) -> [u8; 32];
    /// Execute a short UI operation on GPUI foreground. `None` selects the
    /// asynchronous worker path. UI handlers must not perform blocking I/O.
    fn invoke_foreground(
        &self,
        _function_id: u32,
        _args: &[u8],
        _window: &mut gpui::Window,
        _cx: &mut gpui::App,
    ) -> Option<Result<Vec<u8>, String>> {
        None
    }
    /// Blocking convenience for tests and worker threads; never call from GPUI
    /// foreground. Generated dispatchers reject calls from within Tokio.
    fn invoke(&self, function_id: u32, args: &[u8]) -> Result<Vec<u8>, String>;
    /// Generated dispatchers abort the Tokio task when this future is dropped.
    /// Custom dispatchers must supply their own execution/cancellation policy.
    fn invoke_async(
        &self,
        function_id: u32,
        args: Vec<u8>,
    ) -> futures::future::BoxFuture<'_, Result<Vec<u8>, String>> {
        Box::pin(async move { self.invoke(function_id, &args) })
    }
}

mod cancellation;
mod component;
#[cfg(not(target_family = "wasm"))]
mod executor;
#[cfg(target_family = "wasm")]
#[path = "executor_web.rs"]
mod executor;
pub use cancellation::NativeCallContext;
mod json_guard;
mod module;
pub use component::*;
pub use module::*;

use serde::de::DeserializeOwned;
use std::{
    collections::{BTreeMap, BTreeSet},
    io::{self, Write},
};
use ts_rs::{Config, TypeVisitor};

pub fn decode_json<T: DeserializeOwned>(bytes: &[u8]) -> Result<T, String> {
    if bytes.len() > MAX_NATIVE_CALL_BYTES {
        return Err("native value exceeds 1 MiB".into());
    }
    let value: serde_json::Value =
        serde_json::from_slice(bytes).map_err(|e| format!("invalid native JSON: {e}"))?;
    value
        .serialize(json_guard::Guard)
        .map_err(|e| e.to_string())?;
    let mut ignored = None;
    let mut deserializer = serde_json::Deserializer::from_slice(bytes);
    let value =
        serde_ignored::deserialize(&mut deserializer, |path| ignored = Some(path.to_string()))
            .map_err(|e| format!("invalid native value: {e}"))?;
    deserializer
        .end()
        .map_err(|e| format!("invalid native JSON: {e}"))?;
    if let Some(path) = ignored {
        return Err(format!("unknown native field: {path}"));
    }
    Ok(value)
}

pub fn encode_json<T: Serialize + ?Sized>(value: &T) -> Result<Vec<u8>, String> {
    value
        .serialize(json_guard::Guard)
        .map_err(|e| e.to_string())?;
    let mut writer = BoundedWriter(Vec::new());
    serde_json::to_writer(&mut writer, value).map_err(|e| e.to_string())?;
    Ok(writer.0)
}
struct BoundedWriter(Vec<u8>);
impl Write for BoundedWriter {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        if bytes.len() > MAX_NATIVE_CALL_BYTES - self.0.len() {
            return Err(io::Error::other("native value exceeds 1 MiB"));
        }
        self.0.extend_from_slice(bytes);
        Ok(bytes.len())
    }
    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

#[derive(Default)]
pub struct Types {
    pub(crate) declarations: BTreeMap<String, String>,
    visited: BTreeSet<&'static str>,
    names: BTreeSet<String>,
}
impl TypeVisitor for Types {
    fn visit<T: TS + ?Sized + 'static>(&mut self) {
        if !self.visited.insert(std::any::type_name::<T>()) {
            return;
        }
        let config = Config::new();
        if T::output_path().is_some() {
            let name = T::ident(&config);
            let decl = T::decl(&config);
            if let Some(previous) = self.declarations.insert(name.clone(), decl.clone()) {
                assert_eq!(previous, decl, "conflicting exported native type {name}");
            }
        }
        T::visit_dependencies(self);
        T::visit_generics(self);
    }
}
impl Types {
    pub fn collect<T: TS + 'static>(&mut self) -> String {
        self.visit::<T>();
        let name = T::name(&Config::new());
        self.names.insert(name.clone());
        name
    }
    pub(crate) fn check(&self) -> Result<(), String> {
        for decl in self.declarations.values().chain(self.names.iter()) {
            if decl
                .split(|c: char| !c.is_alphanumeric() && c != '_')
                .any(|s| s == "bigint" || s == "any")
            {
                return Err("native DTOs do not support bigint or any; use bounded values or explicit strings".into());
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod children_tests;
