[workspace]
resolver = "2"
members = [
    "crates/react-gpui",
    "crates/react-gpui-host",
    "crates/react-gpui-bun",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "0.2.0"
description = "React GPUI renders React trees into one or more native GPUI surfaces."
keywords = ["react", "gpui", "native-ui"]
categories = ["gui"]

repository = "https://github.com/Cyenoch/react-gpui"
readme = "README.md"

[workspace.dependencies]
futures = "0.3"
gpui = "0.2.2"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.19"
skrifa = { version = "0.44", default-features = false, features = ["std"] }
thiserror = "2.0"
unicode-segmentation = "1.13.3"
[patch.crates-io]
gpui = { git = "https://github.com/zed-industries/zed", rev = "6805d952f9f3d702f760aa11b1547df8a625fa16", package = "gpui", version = "=0.2.2" }

[profile.dev]
debug = 1

[profile.release]
lto = "thin"
codegen-units = 1
