/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ComponentsSplatRouteImport } from "./routes/components.$";
import { Route as DocsSplatRouteImport } from "./routes/docs.$";
import { Route as ShowcaseSplatRouteImport } from "./routes/showcase.$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ComponentsSplatRoute = ComponentsSplatRouteImport.update({
  id: "/components/$",
  path: "/components/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ShowcaseSplatRoute = ShowcaseSplatRouteImport.update({
  id: "/showcase/$",
  path: "/showcase/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/components/$": typeof ComponentsSplatRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/showcase/$": typeof ShowcaseSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/components/$": typeof ComponentsSplatRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/showcase/$": typeof ShowcaseSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/components/$": typeof ComponentsSplatRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/showcase/$": typeof ShowcaseSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/components/$" | "/docs/$" | "/showcase/$";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/components/$" | "/docs/$" | "/showcase/$";
  id: "__root__" | "/" | "/components/$" | "/docs/$" | "/showcase/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ComponentsSplatRoute: typeof ComponentsSplatRoute;
  DocsSplatRoute: typeof DocsSplatRoute;
  ShowcaseSplatRoute: typeof ShowcaseSplatRoute;
}

declare module "@solid-gpui/router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/components/$": {
      id: "/components/$";
      path: "/components/$";
      fullPath: "/components/$";
      preLoaderRoute: typeof ComponentsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/docs/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/showcase/$": {
      id: "/showcase/$";
      path: "/showcase/$";
      fullPath: "/showcase/$";
      preLoaderRoute: typeof ShowcaseSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsSplatRoute: ComponentsSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  ShowcaseSplatRoute: ShowcaseSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
