import { recipes } from "./shared";

export const controlsRecipes = [
  ...recipes("Checkbox", [
    {
      id: "states",
      title: "Checked and disabled",
      description: "Compare available and unavailable choices in both states.",
      jsx: '<N.Checkbox label="Enable notifications" checked={enabled()} onChange={setEnabled} /><N.Checkbox label="Managed by your team" checked disabled /><N.Checkbox label="Not available" disabled />',
      setup: "const [enabled, setEnabled] = createSignal(false);",
    },
    {
      id: "sizes",
      title: "Control sizes",
      description: "Use compact controls in dense settings and larger controls in forms.",
      jsx: '<N.Checkbox label="Xsmall" size="xsmall" checked={enabled()} onChange={setEnabled} /><N.Checkbox label="Small" size="small" checked={enabled()} onChange={setEnabled} /><N.Checkbox label="Medium" size="medium" checked={enabled()} onChange={setEnabled} /><N.Checkbox label="Large" size="large" checked={enabled()} onChange={setEnabled} />',
      setup: "const [enabled, setEnabled] = createSignal(true);",
    },
  ]),
  ...recipes("Switch", [
    {
      id: "states",
      title: "Checked and disabled",
      description: "Compare available and unavailable choices in both states.",
      jsx: '<N.Switch label="Enable notifications" checked={enabled()} onChange={setEnabled} /><N.Switch label="Managed by your team" checked disabled /><N.Switch label="Not available" disabled />',
      setup: "const [enabled, setEnabled] = createSignal(false);",
    },
    {
      id: "sizes",
      title: "Control sizes",
      description: "Use compact controls in dense settings and larger controls in forms.",
      jsx: '<N.Switch label="Xsmall" size="xsmall" checked={enabled()} onChange={setEnabled} /><N.Switch label="Small" size="small" checked={enabled()} onChange={setEnabled} /><N.Switch label="Medium" size="medium" checked={enabled()} onChange={setEnabled} /><N.Switch label="Large" size="large" checked={enabled()} onChange={setEnabled} />',
      setup: "const [enabled, setEnabled] = createSignal(true);",
    },
  ]),
  ...recipes("Radio", [
    {
      id: "states",
      title: "Checked and disabled",
      description: "Compare available and unavailable choices in both states.",
      jsx: '<N.Radio label="Enable notifications" checked={enabled()} onChange={setEnabled} /><N.Radio label="Managed by your team" checked disabled /><N.Radio label="Not available" disabled />',
      setup: "const [enabled, setEnabled] = createSignal(false);",
    },
    {
      id: "sizes",
      title: "Control sizes",
      description: "Use compact controls in dense settings and larger controls in forms.",
      jsx: '<N.Radio label="Xsmall" size="xsmall" checked={enabled()} onChange={setEnabled} /><N.Radio label="Small" size="small" checked={enabled()} onChange={setEnabled} /><N.Radio label="Medium" size="medium" checked={enabled()} onChange={setEnabled} /><N.Radio label="Large" size="large" checked={enabled()} onChange={setEnabled} />',
      setup: "const [enabled, setEnabled] = createSignal(true);",
    },
  ]),
  ...recipes("Toggle", [
    {
      id: "states",
      title: "Checked and disabled",
      description: "Compare available and unavailable choices in both states.",
      jsx: '<N.Toggle label="Enable notifications" checked={enabled()} onChange={setEnabled} /><N.Toggle label="Managed by your team" checked disabled /><N.Toggle label="Not available" disabled />',
      setup: "const [enabled, setEnabled] = createSignal(false);",
    },
    {
      id: "sizes",
      title: "Control sizes",
      description: "Use compact controls in dense settings and larger controls in forms.",
      jsx: '<N.Toggle label="Xsmall" size="xsmall" checked={enabled()} onChange={setEnabled} /><N.Toggle label="Small" size="small" checked={enabled()} onChange={setEnabled} /><N.Toggle label="Medium" size="medium" checked={enabled()} onChange={setEnabled} /><N.Toggle label="Large" size="large" checked={enabled()} onChange={setEnabled} />',
      setup: "const [enabled, setEnabled] = createSignal(true);",
    },
    {
      id: "outline",
      title: "Outlined toggle",
      description: "Keep the toggle boundary visible before it is selected.",
      jsx: '<N.Toggle label="Bold" outline checked={bold()} onChange={setBold} />',
      setup: "const [bold, setBold] = createSignal(false);",
    },
  ]),
  ...recipes("ButtonGroup", [
    {
      id: "vertical",
      title: "Vertical actions",
      description: "Stack related actions when horizontal space is limited.",
      jsx: '<N.ButtonGroup orientation="vertical" outline><N.Button label="Cut" /><N.Button label="Copy" /><N.Button label="Paste" disabled /></N.ButtonGroup>',
      setup: "",
    },
    {
      id: "selection",
      title: "Multiple selection",
      description: "Allow independent formatting choices within one group.",
      jsx: '<N.ButtonGroup multiple onChange={setSelected}><N.Button label="Bold" selected={selected().includes(0)} /><N.Button label="Italic" selected={selected().includes(1)} /><N.Button label="Underline" selected={selected().includes(2)} /></N.ButtonGroup><N.Label text={`${selected().length} styles selected`} />',
      setup: "const [selected, setSelected] = createSignal<number[]>([]);",
    },
  ]),
  ...recipes("RadioGroup", [
    {
      id: "choices",
      title: "Grouped preferences",
      description: "Keep related choices together and reflect changes in Solid state.",
      jsx: '<N.RadioGroup orientation="vertical" selectedIndex={selected()} onChange={setSelected}><N.Radio label="Personal" /><N.Radio label="Team" /><N.Radio label="Enterprise" disabled /></N.RadioGroup>',
      setup: "const [selected, setSelected] = createSignal(0);",
    },
    {
      id: "disabled",
      title: "Unavailable group",
      description: "Disable the entire group when a preference is managed elsewhere.",
      jsx: '<N.RadioGroup disabled size="small"><N.Radio label="Personal" checked /><N.Radio label="Team" /></N.RadioGroup>',
      setup: "",
    },
  ]),
  ...recipes("ToggleGroup", [
    {
      id: "choices",
      title: "Grouped preferences",
      description: "Keep related choices together and reflect changes in Solid state.",
      jsx: '<N.ToggleGroup segmented onChange={setFlags}><N.Toggle label="Bold" checked={flags()[0]} /><N.Toggle label="Italic" checked={flags()[1]} /><N.Toggle label="Underline" checked={flags()[2]} /></N.ToggleGroup>',
      setup: "const [flags, setFlags] = createSignal([false, false, false]);",
    },
    {
      id: "disabled",
      title: "Unavailable group",
      description: "Disable the entire group when a preference is managed elsewhere.",
      jsx: '<N.ToggleGroup disabled size="small"><N.Toggle label="Bold" checked /><N.Toggle label="Italic" /></N.ToggleGroup>',
      setup: "",
    },
  ]),
  ...recipes("Input", [
    {
      id: "password",
      title: "Password input",
      description: "Mask sensitive text and let the user reveal it when needed.",
      jsx: '<N.Input placeholder="Password" masked maskToggle ariaLabel="Password" />',
      setup: "",
    },
    {
      id: "adornments",
      title: "Prefix and suffix",
      description: "Put a unit or action beside the editable value.",
      jsx: '<N.Input placeholder="your-site" slots={{ prefix: <N.Label text="https://" />, suffix: <N.Label text=".com" /> }} /><N.Input placeholder="Search projects" cleanable />',
      setup: "",
    },
    {
      id: "readonly",
      title: "Read-only and disabled",
      description: "Read-only values remain readable; disabled fields indicate unavailable editing.",
      jsx: '<N.Input defaultValue="Project notes" readonly /><N.Input defaultValue="Project notes" disabled />',
      setup: "",
    },
    {
      id: "sizes",
      title: "Field sizes",
      description: "Choose a field size that matches nearby labels and buttons.",
      jsx: '<N.Input placeholder="Small" size="small" /><N.Input placeholder="Medium" size="medium" /><N.Input placeholder="Large" size="large" />',
      setup: "",
    },
  ]),
  ...recipes("Textarea", [
    {
      id: "readonly",
      title: "Read-only and disabled",
      description: "Read-only values remain readable; disabled fields indicate unavailable editing.",
      jsx: '<N.Textarea defaultValue="Project notes" readonly /><N.Textarea defaultValue="Project notes" disabled />',
      setup: "",
    },
    {
      id: "autogrow",
      title: "Growing text area",
      description: "Let a short message grow into multiple lines without taking unnecessary space.",
      jsx: '<N.Textarea placeholder="Write a message…" autoGrow={{ minRows: 2, maxRows: 6 }} /><N.Label text="The field grows up to six rows." />',
      setup: "",
    },
    {
      id: "controlled",
      title: "Character count",
      description: "Keep a live character count next to a controlled text area.",
      jsx: '<N.Textarea value={value()} onChange={event => setValue(event.value)} rows={3} placeholder="Tell us about your project" /><N.Label text={`${value().length} characters`} />',
      setup: 'const [value, setValue] = createSignal("");',
    },
  ]),
  ...recipes("Editor", [
    {
      id: "readonly",
      title: "Read-only and disabled",
      description: "Read-only values remain readable; disabled fields indicate unavailable editing.",
      jsx: '<N.Editor defaultValue="Project notes" readonly /><N.Editor defaultValue="Project notes" disabled />',
      setup: "",
    },
    {
      id: "code",
      title: "Code editing",
      description: "Show line numbers and indentation guides for structured code.",
      jsx: '<N.Editor language="typescript" defaultValue={"function greet(name: string) {\\n  return `Hello, ${name}`;\\n}"} lineNumbers indentGuides tabSize={2} style={{ height: 220 }} />',
      setup: "",
    },
    {
      id: "wrap",
      title: "Wrapped document",
      description: "Use soft wrapping for prose without horizontal scrolling.",
      jsx: '<N.Editor language="markdown" softWrap lineNumbers={false} defaultValue={"# Project notes\\n\\nA shared document for ideas, decisions, and next steps."} style={{ height: 180 }} />',
      setup: "",
    },
  ]),
  ...recipes("NumberInput", [
    {
      id: "readonly",
      title: "Read-only and disabled",
      description: "Read-only values remain readable; disabled fields indicate unavailable editing.",
      jsx: '<N.NumberInput defaultValue="24" readonly /><N.NumberInput defaultValue="24" disabled />',
      setup: "",
    },
    {
      id: "sizes",
      title: "Field sizes",
      description: "Choose a field size that matches nearby labels and buttons.",
      jsx: '<N.NumberInput placeholder="Small" size="small" /><N.NumberInput placeholder="Medium" size="medium" /><N.NumberInput placeholder="Large" size="large" />',
      setup: "",
    },
    {
      id: "units",
      title: "Units and steps",
      description: "Constrain a quantity and display its unit next to the value.",
      jsx: '<N.NumberInput defaultValue="50" min={0} max={100} step={5} slots={{ suffix: <N.Label text="%" /> }} /><N.NumberInput defaultValue="12" min={1} max={24} slots={{ prefix: <N.Label text="Seats" /> }} />',
      setup: "",
    },
  ]),
  ...recipes("OtpInput", [
    {
      id: "groups",
      title: "Grouped verification code",
      description: "Separate a code into readable groups.",
      jsx: '<N.OtpInput length={6} groups={2} size="small" onComplete={setCode} /><N.Label text={code() ? "Code complete" : "Enter six digits"} />',
      setup: 'const [code, setCode] = createSignal("");',
    },
    {
      id: "masked",
      title: "Masked code",
      description: "Hide the entered digits for a private verification step.",
      jsx: '<N.OtpInput length={4} masked /><N.OtpInput length={4} defaultValue="1234" disabled />',
      setup: "",
    },
  ]),
  ...recipes("Slider", [
    {
      id: "range",
      title: "Range selection",
      description: "Let users choose both ends of a range.",
      jsx: '<N.Slider defaultValue={{ kind: "range", start: 20, end: 70 }} min={0} max={100} step={5} />',
      setup: "",
    },
    {
      id: "steps",
      title: "Stepped values",
      description: "Snap to useful increments and show an unavailable comparison.",
      jsx: '<N.Slider defaultValue={{ kind: "single", value: 50 }} step={10} /><N.Slider defaultValue={{ kind: "single", value: 50 }} disabled />',
      setup: "",
    },
    {
      id: "vertical",
      title: "Vertical slider",
      description: "Use a vertical control for levels such as volume.",
      jsx: '<View style={{ height: 180, alignItems: "center" }}><N.Slider vertical defaultValue={{ kind: "single", value: 60 }} /></View>',
      setup: "",
    },
  ]),
  ...recipes("Rating", [
    {
      id: "readonly",
      title: "Rating summary",
      description: "Display an existing rating without inviting edits.",
      jsx: '<N.Rating value={4} max={5} disabled /><N.Label text="4 out of 5 · 128 reviews" />',
      setup: "",
    },
    {
      id: "scale",
      title: "Custom rating scale",
      description: "Choose a smaller scale and a status color for quick feedback.",
      jsx: '<N.Rating value={rating()} max={3} color="#f59e0b" size="large" onChange={setRating} />',
      setup: "const [rating, setRating] = createSignal(2);",
    },
  ]),
  ...recipes("Select", [
    {
      id: "search",
      title: "Searchable choices",
      description: "Find a teammate by typing and clear the selection when needed.",
      jsx: '<N.Select items={[{ key: "team", label: "Team", items: [{ key: "alex", label: "Alex Chen" }, { key: "sam", label: "Sam Rivera" }, { key: "taylor", label: "Taylor Kim", disabled: true }] }]} searchable cleanable placeholder="Assign a teammate" />',
      setup: "",
    },
    {
      id: "disabled",
      title: "Disabled choices",
      description: "Show the current assignment when changes are unavailable.",
      jsx: '<N.Select items={[{ key: "team", label: "Team", items: [{ key: "alex", label: "Alex Chen" }, { key: "sam", label: "Sam Rivera" }, { key: "taylor", label: "Taylor Kim", disabled: true }] }]} defaultValue="alex" disabled />',
      setup: "",
    },
  ]),
  ...recipes("Combobox", [
    {
      id: "search",
      title: "Searchable choices",
      description: "Find a teammate by typing and clear the selection when needed.",
      jsx: '<N.Combobox items={[{ key: "team", label: "Team", items: [{ key: "alex", label: "Alex Chen" }, { key: "sam", label: "Sam Rivera" }, { key: "taylor", label: "Taylor Kim", disabled: true }] }]} searchable cleanable placeholder="Assign a teammate" />',
      setup: "",
    },
    {
      id: "disabled",
      title: "Disabled choices",
      description: "Show the current assignment when changes are unavailable.",
      jsx: '<N.Combobox items={[{ key: "team", label: "Team", items: [{ key: "alex", label: "Alex Chen" }, { key: "sam", label: "Sam Rivera" }, { key: "taylor", label: "Taylor Kim", disabled: true }] }]} defaultValues={["alex"]} disabled />',
      setup: "",
    },
    {
      id: "multiple",
      title: "Multiple assignees",
      description: "Select several people from the same searchable list.",
      jsx: '<N.Combobox items={[{ key: "team", label: "Team", items: [{ key: "alex", label: "Alex Chen" }, { key: "sam", label: "Sam Rivera" }, { key: "taylor", label: "Taylor Kim", disabled: true }] }]} multiple searchable defaultValues={["alex", "sam"]} placeholder="Choose teammates" />',
      setup: "",
    },
  ]),
  ...recipes("Calendar", [
    {
      id: "range",
      title: "Date range",
      description: "Choose the start and end of a trip or reporting period.",
      jsx: '<N.Calendar defaultValue={{ kind: "range", start: "2026-09-07", end: "2026-09-14" }} />',
      setup: "",
    },
    {
      id: "restricted",
      title: "Available dates",
      description: "Exclude weekends when scheduling a working day.",
      jsx: '<N.Calendar defaultValue={{ kind: "single", date: "2026-09-07" }} firstDayOfWeek={1} disabledDates={{ weekdays: [0, 6] }} />',
      setup: "",
    },
  ]),
  ...recipes("DatePicker", [
    {
      id: "range",
      title: "Date range",
      description: "Choose the start and end of a trip or reporting period.",
      jsx: '<N.DatePicker defaultValue={{ kind: "range", start: "2026-09-07", end: "2026-09-14" }} />',
      setup: "",
    },
    {
      id: "restricted",
      title: "Available dates",
      description: "Exclude weekends when scheduling a working day.",
      jsx: '<N.DatePicker defaultValue={{ kind: "single", date: "2026-09-07" }} firstDayOfWeek={1} disabledDates={{ weekdays: [0, 6] }} />',
      setup: "",
    },
    {
      id: "clear",
      title: "Clearable date",
      description: "Let an optional date return to an empty state.",
      jsx: '<N.DatePicker cleanable placeholder="Optional due date" /><N.DatePicker disabled placeholder="Not scheduled" />',
      setup: "",
    },
  ]),
  ...recipes("ColorPicker", [
    {
      id: "palette",
      title: "Curated palette",
      description: "Offer a small set of colors that fit the product.",
      jsx: '<N.ColorPicker label="Project color" defaultValue="#3b82f6" featuredColors={["#3b82f6", "#10b981", "#f59e0b", "#ef4444", "#8b5cf6"]} />',
      setup: "",
    },
    {
      id: "sizes",
      title: "Compact color control",
      description: "Use a small picker alongside other toolbar controls.",
      jsx: '<N.ColorPicker label="Accent" size="small" defaultValue="#10b981" /><N.ColorPicker label="Highlight" size="large" defaultValue="#f59e0b" />',
      setup: "",
    },
  ]),
];
