import { recipes } from "./shared";

export const presentationRecipes = [
  ...recipes("Alert", [
    {
      id: "info",
      title: "Information",
      description: "Match the message severity to the situation.",
      jsx: '<N.Alert title="Information" message="Your trial includes all features." variant="info" />',
      setup: "",
    },
    {
      id: "success",
      title: "Success",
      description: "Match the message severity to the situation.",
      jsx: '<N.Alert title="Success" message="Your changes have been saved." variant="success" />',
      setup: "",
    },
    {
      id: "warning",
      title: "Warning",
      description: "Match the message severity to the situation.",
      jsx: '<N.Alert title="Warning" message="Your storage is almost full." variant="warning" />',
      setup: "",
    },
    {
      id: "error",
      title: "Error",
      description: "Match the message severity to the situation.",
      jsx: '<N.Alert title="Error" message="The upload could not be completed." variant="error" />',
      setup: "",
    },
    {
      id: "banner",
      title: "Dismissible banner",
      description: "Use a full-width notice for information that affects the whole view.",
      jsx: '<N.Alert banner visible={visible()} title="Scheduled maintenance" message="Service resumes at 09:00." onClose={() => setVisible(false)} /><N.Button label="Show notice" onPress={() => setVisible(true)} />',
      setup: "const [visible, setVisible] = createSignal(true);",
    },
  ]),
  ...recipes("Avatar", [
    {
      id: "sizes",
      title: "Avatar sizes",
      description: "Use initials when a profile has no image.",
      jsx: '<N.AvatarGroup size="small"><N.Avatar name="Alex Chen" /><N.Avatar name="Sam Rivera" /></N.AvatarGroup><N.AvatarGroup size="large"><N.Avatar name="Alex Chen" /><N.Avatar name="Sam Rivera" /></N.AvatarGroup>',
      setup: "",
    },
    {
      id: "overflow",
      title: "Group overflow",
      description: "Limit visible avatars while keeping the group compact.",
      jsx: '<N.AvatarGroup limit={2} ellipsis><N.Avatar name="Alex Chen" /><N.Avatar name="Sam Rivera" /><N.Avatar name="Taylor Kim" /><N.Avatar name="Jordan Lee" /></N.AvatarGroup>',
      setup: "",
    },
  ]),
  ...recipes("AvatarGroup", [
    {
      id: "sizes",
      title: "Avatar sizes",
      description: "Use initials when a profile has no image.",
      jsx: '<N.AvatarGroup size="small"><N.Avatar name="Alex Chen" /><N.Avatar name="Sam Rivera" /></N.AvatarGroup><N.AvatarGroup size="large"><N.Avatar name="Alex Chen" /><N.Avatar name="Sam Rivera" /></N.AvatarGroup>',
      setup: "",
    },
    {
      id: "overflow",
      title: "Group overflow",
      description: "Limit visible avatars while keeping the group compact.",
      jsx: '<N.AvatarGroup limit={2} ellipsis><N.Avatar name="Alex Chen" /><N.Avatar name="Sam Rivera" /><N.Avatar name="Taylor Kim" /><N.Avatar name="Jordan Lee" /></N.AvatarGroup>',
      setup: "",
    },
  ]),
  ...recipes("Badge", [
    {
      id: "count",
      title: "Count limit",
      description: "Keep large notification counts readable with a maximum label.",
      jsx: '<View style={{ alignItems: "center", gap: 24 }}><N.Badge count={128} max={99}><N.Button label="Inbox" /></N.Badge><N.Badge count={3}><N.Button label="Updates" /></N.Badge></View>',
      setup: "",
    },
    {
      id: "dot",
      title: "Status dot",
      description: "Use a dot when the presence of an update matters more than its count.",
      jsx: '<View style={{ alignItems: "center" }}><N.Badge dot color="#10b981"><N.Avatar name="Alex Chen" /></N.Badge></View>',
      setup: "",
    },
  ]),
  ...recipes("Tag", [
    {
      id: "variants",
      title: "Status labels",
      description: "Assign distinct meanings to success, warning, information, and danger.",
      jsx: '<View style={{ alignItems: "flex-start", gap: 12 }}><N.Tag variant="primary"><N.Text value="New" /></N.Tag><N.Tag variant="secondary"><N.Text value="Draft" /></N.Tag><N.Tag variant="success"><N.Text value="Published" /></N.Tag><N.Tag variant="warning"><N.Text value="Pending" /></N.Tag><N.Tag variant="danger"><N.Text value="Failed" /></N.Tag><N.Tag variant="info"><N.Text value="Scheduled" /></N.Tag></View>',
      setup: "",
    },
    {
      id: "outline",
      title: "Outlined labels",
      description: "Use outlines for a quieter set of categories.",
      jsx: '<View style={{ alignItems: "flex-start", gap: 12 }}><N.Tag outline variant="info"><N.Text value="Design" /></N.Tag><N.Tag outline rounded variant="success"><N.Text value="Engineering" /></N.Tag></View>',
      setup: "",
    },
    {
      id: "sizes",
      title: "Label sizes",
      description: "Match category labels to dense rows or larger detail views.",
      jsx: '<View style={{ alignItems: "flex-start", gap: 12 }}><N.Tag size="small"><N.Text value="Small" /></N.Tag><N.Tag size="medium"><N.Text value="Medium" /></N.Tag><N.Tag size="large"><N.Text value="Large" /></N.Tag></View>',
      setup: "",
    },
  ]),
  ...recipes("Progress", [
    {
      id: "values",
      title: "Progress stages",
      description: "Compare an empty, partial, and completed operation.",
      jsx: "<N.Progress value={0} /><N.Progress value={35} /><N.Progress value={100} />",
      setup: "",
    },
    {
      id: "interactive",
      title: "Update progress",
      description: "Advance progress from an action and reset it for another run.",
      jsx: '<N.Progress value={progress()} /><N.Label text={`${progress()}% complete`} /><N.Button label={progress() === 100 ? "Start again" : "Advance"} onPress={() => setProgress(progress() === 100 ? 0 : Math.min(100, progress() + 25))} />',
      setup: "const [progress, setProgress] = createSignal(25);",
    },
  ]),
  ...recipes("ProgressCircle", [
    {
      id: "values",
      title: "Progress stages",
      description: "Compare an empty, partial, and completed operation.",
      jsx: "<N.ProgressCircle value={0} /><N.ProgressCircle value={35} /><N.ProgressCircle value={100} />",
      setup: "",
    },
    {
      id: "interactive",
      title: "Update progress",
      description: "Advance progress from an action and reset it for another run.",
      jsx: '<N.ProgressCircle value={progress()} /><N.Label text={`${progress()}% complete`} /><N.Button label={progress() === 100 ? "Start again" : "Advance"} onPress={() => setProgress(progress() === 100 ? 0 : Math.min(100, progress() + 25))} />',
      setup: "const [progress, setProgress] = createSignal(25);",
    },
    {
      id: "color",
      title: "Colored progress",
      description: "Use a status color and accessible label for a circular indicator.",
      jsx: '<N.ProgressCircle value={75} size="large" color="#10b981" accessibilityLabel="Upload 75 percent complete" />',
      setup: "",
    },
  ]),
  ...recipes("Spinner", [
    {
      id: "sizes",
      title: "Spinner sizes",
      description: "Match the indicator to the space reserved for loading.",
      jsx: '<View style={{ flexDirection: "row", gap: 20, alignItems: "center" }}><N.Spinner size="small" /><N.Spinner size="medium" /><N.Spinner size="large" /></View>',
      setup: "",
    },
    {
      id: "inline",
      title: "Inline loading",
      description: "Pair the indicator with a description of the ongoing work.",
      jsx: '<View style={{ flexDirection: "row", gap: 12, alignItems: "center" }}><N.Spinner size="small" /><N.Label text="Syncing your workspace…" /></View>',
      setup: "",
    },
  ]),
  ...recipes("Skeleton", [
    {
      id: "profile",
      title: "Profile placeholder",
      description: "Reserve the avatar and text layout before profile data arrives.",
      jsx: '<View style={{ flexDirection: "row", gap: 12 }}><N.Skeleton style={{ width: 40, height: 40, borderRadius: 20 }} /><View style={{ gap: 8, flexGrow: 1 }}><N.Skeleton style={{ height: 14, width: 150 }} /><N.Skeleton secondary style={{ height: 14, width: 190 }} /></View></View>',
      setup: "",
    },
    {
      id: "card",
      title: "Card placeholder",
      description: "Keep the image and description positions stable during loading.",
      jsx: "<N.Skeleton style={{ height: 140, borderRadius: 8 }} /><N.Skeleton style={{ height: 16, width: 160 }} /><N.Skeleton secondary style={{ height: 12, width: 190 }} />",
      setup: "",
    },
  ]),
  ...recipes("ShimmerText", [
    {
      id: "once",
      title: "One-time shimmer",
      description: "Run the highlight once for a newly available status.",
      jsx: '<N.ShimmerText text="Your workspace is ready" once durationMs={1800} color="#ffffff" style={{ color: "#52525b", fontSize: 22 }} />',
      setup: "",
    },
    {
      id: "direction",
      title: "Shimmer direction",
      description: "Change the direction and duration to fit the status treatment.",
      jsx: '<N.ShimmerText text="Preparing your report…" reverse durationMs={2400} color="#ffffff" style={{ color: "#52525b", fontSize: 22 }} />',
      setup: "",
    },
  ]),
  ...recipes("Label", [
    {
      id: "secondary",
      title: "Secondary information",
      description: "Put supporting information next to the primary label.",
      jsx: '<N.Label text="Storage" secondary="2.4 GB of 10 GB" /><N.Label text="Workspace" secondary="Personal plan" />',
      setup: "",
    },
    {
      id: "highlight",
      title: "Highlighted match",
      description: "Emphasize the part of a label that matches a search.",
      jsx: '<N.Label text="Project settings" highlight="settings" /><N.Label text="Private access token" masked />',
      setup: "",
    },
  ]),
  ...recipes("Text", [
    {
      id: "typography",
      title: "Text hierarchy",
      description: "Give a title, description, and metadata distinct visual roles.",
      jsx: '<N.Text value="Workspace activity" style={{ fontSize: 24, fontWeight: "semibold" }} /><N.Text value="Keep track of the latest changes." /><N.Text value="Updated a moment ago" style={{ fontSize: 12, color: "#a1a1aa" }} />',
      setup: "",
    },
    {
      id: "wrapping",
      title: "Long content",
      description: "Let descriptions wrap within the available width.",
      jsx: '<N.Text value="A shared workspace brings project notes, decisions, and conversations into one place so everyone can follow the work." />',
      setup: "",
    },
  ]),
  ...recipes("TextView", [
    {
      id: "markdown",
      title: "Markdown content",
      description: "Render headings, emphasis, lists, and links in a selectable document.",
      jsx: '<N.TextView format="markdown" selectable text={"## Release notes\\n\\nA **faster** workspace.\\n\\n- Improved navigation\\n- Clearer status messages\\n\\n[Read the source](https://github.com/Cyenoch/solid-gpui)"} />',
      setup: "",
    },
    {
      id: "bounded",
      title: "Bounded document",
      description: "Keep a long document inside a scrollable reading area.",
      jsx: '<N.TextView format="markdown" selectable scrollable text={Array.from({ length: 12 }, (_, i) => `### Note ${i + 1}\\n\\nA short update from the project.`).join("\\n\\n")} style={{ height: 220 }} />',
      setup: "",
    },
  ]),
  ...recipes("Icon", [
    {
      id: "sizes",
      title: "Indicator sizes",
      description: "Keep indicators proportional to the controls they accompany.",
      jsx: '<View style={{ flexDirection: "row", gap: 20, alignItems: "center" }}><N.Icon path="icons/check.svg" size="small" /><N.Icon path="icons/check.svg" size="medium" /><N.Icon path="icons/check.svg" size="large" /></View>',
      setup: "",
    },
    {
      id: "color",
      title: "Indicator color",
      description: "Use a semantic color to reinforce the current status.",
      jsx: '<N.Icon path="icons/check.svg" color="#10b981" /><N.Icon path="icons/check.svg" color="#f59e0b" />',
      setup: "",
    },
  ]),
  ...recipes("Caret", [
    {
      id: "sizes",
      title: "Indicator sizes",
      description: "Keep indicators proportional to the controls they accompany.",
      jsx: '<View style={{ flexDirection: "row", gap: 20, alignItems: "center" }}><N.Caret  size="small" /><N.Caret  size="medium" /><N.Caret  size="large" /></View>',
      setup: "",
    },
    {
      id: "color",
      title: "Indicator color",
      description: "Use a semantic color to reinforce the current status.",
      jsx: '<N.Caret  color="#10b981" /><N.Caret  color="#f59e0b" />',
      setup: "",
    },
  ]),
  ...recipes("Kbd", [
    {
      id: "shortcuts",
      title: "Common shortcuts",
      description: "Show platform-aware modifiers beside familiar commands.",
      jsx: '<N.Label text="Search" /><N.Kbd stroke="secondary-k" /><N.Label text="Command palette" /><N.Kbd stroke="secondary-shift-p" />',
      setup: "",
    },
    {
      id: "outline",
      title: "Shortcut appearance",
      description: "Use an outlined or plain shortcut hint to match the surrounding controls.",
      jsx: '<N.Kbd stroke="secondary-s" outline /><N.Kbd stroke="escape" appearance={false} />',
      setup: "",
    },
  ]),
  ...recipes("Link", [
    {
      id: "action",
      title: "Link action",
      description: "Handle an in-app action from a text link.",
      jsx: '<N.Link onPress={() => setExpanded(!expanded())}><N.Label text={expanded() ? "Hide details" : "Show details"} /></N.Link>{expanded() ? <N.Label text="Your workspace is visible only to invited members." /> : null}',
      setup: "const [expanded, setExpanded] = createSignal(false);",
    },
    {
      id: "disabled",
      title: "Unavailable link",
      description: "Keep a destination visible while access is unavailable.",
      jsx: '<N.Link disabled><N.Label text="Team billing" /></N.Link><N.Label text="Available to workspace owners." />',
      setup: "",
    },
  ]),
  ...recipes("Separator", [
    {
      id: "styles",
      title: "Separator styles",
      description: "Choose a plain, dashed, or labeled divider.",
      jsx: '<N.Separator /><N.Separator dashed /><N.Separator label="Or continue with" />',
      setup: "",
    },
    {
      id: "vertical",
      title: "Vertical separator",
      description: "Separate adjacent actions without introducing another container.",
      jsx: '<View style={{ flexDirection: "row", alignItems: "center", gap: 12, height: 32 }}><N.Label text="Account" /><N.Separator orientation="vertical" /><N.Label text="Settings" /></View>',
      setup: "",
    },
  ]),
  ...recipes("Clipboard", [
    {
      id: "feedback",
      title: "Copy feedback",
      description: "Confirm that the requested value was copied.",
      jsx: '<N.Clipboard value="hello@solid-gpui.dev" tooltip="Copy email address" onCopied={() => setCopied(true)} /><N.Label text={copied() ? "Email copied" : "Copy the contact address"} />',
      setup: "const [copied, setCopied] = createSignal(false);",
    },
    {
      id: "command",
      title: "Copy a command",
      description: "Put a copy action next to the command people need to run.",
      jsx: '<View style={{ flexDirection: "row", gap: 12, alignItems: "center" }}><N.Label text="bun install" /><N.Clipboard value="bun install" tooltip="Copy command" /></View>',
      setup: "",
    },
  ]),
];
