// Generated by the running Rust host. Do not edit.
import { createNativeComponent, createNativeClient, useNativeClient } from "@solid-gpui/core/native";
export type ButtonVariant =
  "default" | "primary" | "secondary" | "danger" | "info" | "success" | "warning" | "ghost" | "link" | "text";
export type ControlSize = "xsmall" | "small" | "medium" | "large";
export type InputChange = { value: string; editSeq: number };
export type InputProps = {
  /**
   * Controlled value: onChange must synchronously accept or transform edits.
   * Use defaultValue and replaceValue for asynchronous validation workflows.
   */
  value?: string | null;
  defaultValue?: string | null;
  placeholder?: string | null;
  disabled?: boolean;
  ackEditSeq?: number;
};
export type Percentage = number;
export type Rounded = "none" | "small" | "medium" | "large";
export type __NativePropsButton = {
  label?: string | null;
  variant?: ButtonVariant;
  disabled?: boolean;
  loading?: boolean;
  compact?: boolean;
  outline?: boolean;
  selected?: boolean;
  toggled?: boolean | null;
  rounded?: Rounded;
  size?: ControlSize;
  tabIndex?: number;
  tabStop?: boolean;
  accessibilityLabel?: string | null;
  dropdownCaret?: boolean;
  tooltip?: string | null;
};
export type __NativePropsCheckbox = {
  checked?: boolean;
  disabled?: boolean;
  label?: string | null;
  accessibilityLabel?: string | null;
  size?: ControlSize;
  tabStop?: boolean;
  tabIndex?: number;
  tooltip?: string | null;
};
export type __NativePropsProgress = { value?: Percentage };
export type __NativePropsSwitch = {
  checked?: boolean;
  disabled?: boolean;
  label?: string | null;
  accessibilityLabel?: string | null;
  size?: ControlSize;
  tooltip?: string | null;
};
export type ButtonRef = {};
export const Button = createNativeComponent<
  __NativePropsButton,
  { onHoverChange?: (value: boolean) => void; onPress?: () => void },
  ButtonRef
>({
  entryId: 1,
  entryVersion: 1,
  controlled: null,
  children: true,
  props: [
    "label",
    "variant",
    "disabled",
    "loading",
    "compact",
    "outline",
    "selected",
    "toggled",
    "rounded",
    "size",
    "tabIndex",
    "tabStop",
    "accessibilityLabel",
    "dropdownCaret",
    "tooltip",
  ],
  events: [
    { id: 1, name: "hoverChange", prop: "onHoverChange" },
    { id: 2, name: "press", prop: "onPress" },
  ],
  commands: [],
  providerId: [33, 84, 240, 222, 90, 144, 85, 111, 58, 12, 212, 208, 10, 14, 46, 196],
  catalogDigest: [
    139, 215, 201, 46, 209, 89, 130, 213, 1, 119, 88, 11, 107, 203, 241, 17, 62, 1, 194, 63, 129, 83, 245, 153, 194, 34,
    78, 250, 203, 46, 207, 185,
  ],
});
export type CheckboxRef = {};
export const Checkbox = createNativeComponent<
  __NativePropsCheckbox,
  { onChange?: (value: boolean) => void },
  CheckboxRef
>({
  entryId: 2,
  entryVersion: 1,
  controlled: null,
  children: true,
  props: ["checked", "disabled", "label", "accessibilityLabel", "size", "tabStop", "tabIndex", "tooltip"],
  events: [{ id: 1, name: "change", prop: "onChange" }],
  commands: [],
  providerId: [33, 84, 240, 222, 90, 144, 85, 111, 58, 12, 212, 208, 10, 14, 46, 196],
  catalogDigest: [
    139, 215, 201, 46, 209, 89, 130, 213, 1, 119, 88, 11, 107, 203, 241, 17, 62, 1, 194, 63, 129, 83, 245, 153, 194, 34,
    78, 250, 203, 46, 207, 185,
  ],
});
export type InputRef = { focus(): Promise<null>; replaceValue(request: string): Promise<null> };
export const Input = createNativeComponent<
  Omit<InputProps, "ackEditSeq">,
  { onChange?: (value: InputChange) => void },
  InputRef
>({
  entryId: 3,
  entryVersion: 1,
  controlled: { valueProp: "value", eventId: 1, sequenceField: "editSeq", ackProp: "ackEditSeq" },
  children: false,
  props: null,
  events: [{ id: 1, name: "change", prop: "onChange" }],
  commands: [
    { id: 1, name: "focus" },
    { id: 2, name: "replaceValue" },
  ],
  providerId: [33, 84, 240, 222, 90, 144, 85, 111, 58, 12, 212, 208, 10, 14, 46, 196],
  catalogDigest: [
    139, 215, 201, 46, 209, 89, 130, 213, 1, 119, 88, 11, 107, 203, 241, 17, 62, 1, 194, 63, 129, 83, 245, 153, 194, 34,
    78, 250, 203, 46, 207, 185,
  ],
});
export type ProgressRef = {};
export const Progress = createNativeComponent<__NativePropsProgress, {}, ProgressRef>({
  entryId: 4,
  entryVersion: 1,
  controlled: null,
  children: false,
  props: ["value"],
  events: [],
  commands: [],
  providerId: [33, 84, 240, 222, 90, 144, 85, 111, 58, 12, 212, 208, 10, 14, 46, 196],
  catalogDigest: [
    139, 215, 201, 46, 209, 89, 130, 213, 1, 119, 88, 11, 107, 203, 241, 17, 62, 1, 194, 63, 129, 83, 245, 153, 194, 34,
    78, 250, 203, 46, 207, 185,
  ],
});
export type SwitchRef = {};
export const Switch = createNativeComponent<__NativePropsSwitch, { onChange?: (value: boolean) => void }, SwitchRef>({
  entryId: 5,
  entryVersion: 1,
  controlled: null,
  children: false,
  props: ["checked", "disabled", "label", "accessibilityLabel", "size", "tooltip"],
  events: [{ id: 1, name: "change", prop: "onChange" }],
  commands: [],
  providerId: [33, 84, 240, 222, 90, 144, 85, 111, 58, 12, 212, 208, 10, 14, 46, 196],
  catalogDigest: [
    139, 215, 201, 46, 209, 89, 130, 213, 1, 119, 88, 11, 107, 203, 241, 17, 62, 1, 194, 63, 129, 83, 245, 153, 194, 34,
    78, 250, 203, 46, 207, 185,
  ],
});
export interface NativeClient0 {}
const descriptor0 = {
  moduleId: [33, 84, 240, 222, 90, 144, 85, 111, 58, 12, 212, 208, 10, 14, 46, 196],
  moduleDigest: [
    139, 215, 201, 46, 209, 89, 130, 213, 1, 119, 88, 11, 107, 203, 241, 17, 62, 1, 194, 63, 129, 83, 245, 153, 194, 34,
    78, 250, 203, 46, 207, 185,
  ],
  commands: [],
};
export const useNative0 = () => useNativeClient<NativeClient0>(descriptor0);
export const createClient0 = (root: Parameters<typeof createNativeClient>[0]) =>
  createNativeClient<NativeClient0>(root, descriptor0);
export type NativeClient = NativeClient0;
export const useNative = (): NativeClient => ({ ...useNative0() });
export const createClient = (root: Parameters<typeof createNativeClient>[0]): NativeClient => ({
  ...createClient0(root),
});
