import { expect, test } from "bun:test";
import { chmod, mkdir, mkdtemp, readFile, realpath, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { tmpdir } from "node:os";
import {
  artifactTargetTriple,
  cargoProfileDirectory,
  expectedExecutablePath,
  readNativeArtifacts,
  recordedHostExecutable,
  serializeNativeArtifacts,
  targetRunsOnHost,
  type NativeArtifacts,
} from "../packages/solid-gpui-vite/src/artifacts";
import {
  exportHostBindings,
  exportNativeBindings,
  prepareNativeHost,
} from "../packages/solid-gpui-vite/src/native-export";
import {
  externalWatchInputs,
  isNativeInput,
  nativeWatchInputs,
  refreshNativeWatchInputs,
} from "../packages/solid-gpui-vite/src/native-watch";
import { checkProject, loadProject, prepareProject, previewApplication } from "../packages/solid-gpui-vite/src/project";

const repo = resolve(import.meta.dir, "..");
const plugin = join(repo, "packages/solid-gpui-vite/src/index.ts");

const LOCKFILE = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4
`;

const HOST_SOURCE = `fn main() {
    if std::env::args().nth(1).as_deref() == Some("--export-native") {
        println!("export const answer=42;");
    }
}
`;

async function fixture(
  prefix: string,
  options: { readonly lockfile?: boolean; readonly buildScript?: boolean } = {},
): Promise<string> {
  const directory = await realpath(await mkdtemp(join(tmpdir(), prefix)));
  await mkdir(join(directory, "src"), { recursive: true });
  await writeFile(
    join(directory, "Cargo.toml"),
    `[package]
name = "native-project-fixture"
version = "0.0.0"
edition = "2024"${options.buildScript ? '\nbuild = "build.rs"' : ""}

[workspace]

[[bin]]
name = "native-project-host"
path = "src/main.rs"
`,
  );
  await writeFile(join(directory, "src/main.rs"), HOST_SOURCE);
  if (options.lockfile !== false) {
    await writeFile(
      join(directory, "Cargo.lock"),
      `${LOCKFILE}
[[package]]
name = "native-project-fixture"
version = "0.0.0"
`,
    );
  }
  await writeFile(join(directory, "package.json"), '{"type":"module"}');
  await writeFile(join(directory, "app.js"), 'import { answer } from "#native";\nconsole.log(answer);\n');
  return directory;
}

function configSource(options: string): string {
  return `import { solidGpui } from ${JSON.stringify(plugin)};
export default { root: import.meta.dirname, plugins: [solidGpui(${options})] };
`;
}

test("prepare publishes bindings, the prepared tsconfig and the artifact record without building the app", async () => {
  const directory = await fixture("solid-project-prepare-");
  const bindings = join(directory, ".generated/native.ts");
  const tsconfig = join(directory, ".solid-gpui/tsconfig.json");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(`{ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }`),
    );
    const prepared = await prepareProject({ root: directory });
    expect(await readFile(bindings, "utf8")).toBe("export const answer = 42;\n");
    // The generated config must map the same specifiers the runtime aliases resolve, and stand on
    // its own: a consumer extends it with only their own strictness and include.
    expect(JSON.parse(await readFile(tsconfig, "utf8"))).toEqual({
      compilerOptions: {
        target: "ES2024",
        module: "preserve",
        moduleResolution: "bundler",
        jsx: "preserve",
        jsxImportSource: "@solid-gpui/core",
        noEmit: true,
        allowImportingTsExtensions: true,
        paths: {
          "#native": [bindings],
          "@solid-gpui/core/components": [bindings],
        },
      },
    });
    expect(prepared.project.aliases).toEqual([
      { find: "#native", replacement: bindings },
      { find: "@solid-gpui/core/components", replacement: bindings },
    ]);
    // Preparing never produces the application bundle.
    await expect(stat(join(directory, "dist"))).rejects.toThrow();

    const artifacts = await readNativeArtifacts(directory);
    expect(artifacts?.native?.profileDirectory).toBe("debug");
    expect(artifacts?.native?.locked).toBe(true);
    expect(artifacts?.native?.bin).toBe("native-project-host");
    expect(artifacts?.bundle).toBe(join(directory, "dist/app.js"));
    // The record's derived expectation must agree with the executable Cargo actually produced.
    expect(expectedExecutablePath(artifacts!)).toBe(artifacts?.native?.executable);
    expect(recordedHostExecutable(artifacts!)).toBe(artifacts?.native?.executable);
    expect(await stat(recordedHostExecutable(artifacts!)!)).toBeTruthy();

    // A production build publishes the same record, now with the bundle it really emitted.
    const { build } = await import("vite");
    await build({ configFile: join(directory, "vite.config.ts"), root: directory, logLevel: "silent" });
    expect(await stat(join(directory, "dist/app.js"))).toBeTruthy();
    const built = await readNativeArtifacts(directory);
    expect(built?.bundle).toBe(join(directory, "dist/app.js"));
    expect(built?.host?.command).toBe(built?.native?.executable);

    await checkProject({ root: directory });
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("check reports every stale generated file and never rewrites one", async () => {
  const directory = await fixture("solid-project-check-");
  const bindings = join(directory, ".generated/native.ts");
  const tsconfig = join(directory, ".solid-gpui/tsconfig.json");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(`{ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }`),
    );
    await prepareProject({ root: directory });
    await writeFile(bindings, "export const answer = 0;\n");
    await rm(tsconfig);
    await expect(checkProject({ root: directory })).rejects.toThrow(/stale/);
    // Verification must not repair what it is verifying.
    expect(await readFile(bindings, "utf8")).toBe("export const answer = 0;\n");
    await expect(stat(tsconfig)).rejects.toThrow();
    await prepareProject({ root: directory });
    expect(await readFile(bindings, "utf8")).toBe("export const answer = 42;\n");
    expect(JSON.parse(await readFile(tsconfig, "utf8")).compilerOptions.paths["#native"]).toEqual([bindings]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("locked defaults to on, and locked:false admits the first lockfile resolution", async () => {
  const directory = await fixture("solid-project-locked-", { lockfile: false });
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(`{ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }`),
    );
    await expect(prepareProject({ root: directory })).rejects.toThrow(/locked/);

    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(
        `{ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host", locked: false } }`,
      ),
    );
    await prepareProject({ root: directory });
    expect(await readFile(join(directory, "Cargo.lock"), "utf8")).toContain("native-project-fixture");
    expect((await readNativeArtifacts(directory))?.native?.locked).toBe(false);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("a cross target is never executed on the build host, and an exporter replaces it", async () => {
  const directory = await fixture("solid-project-target-");
  const output = join(directory, ".generated/native.ts");
  const exporter = join(directory, "exporter.js");
  const foreign = process.platform === "darwin" ? "x86_64-unknown-linux-gnu" : "aarch64-apple-darwin";
  try {
    await writeFile(exporter, 'console.log("export const answer = 7;");\n');
    const options = { manifestPath: join(directory, "Cargo.toml"), bin: "native-project-host", output };
    await expect(exportNativeBindings({ ...options, target: foreign }, directory, process.execPath)).rejects.toThrow(
      /native.exporter|native\.target/,
    );
    await expect(stat(output)).rejects.toThrow();

    await exportNativeBindings(
      {
        ...options,
        target: foreign,
        exporter: { command: process.execPath, args: [exporter] },
      },
      directory,
    );
    expect(await readFile(output, "utf8")).toBe("export const answer = 7;\n");

    // An implicit target (CARGO_BUILD_TARGET or .cargo/config.toml build.target) leaves the same
    // evidence in the artifact path, and must be rejected before the host is executed.
    const implicit = join(directory, "target", foreign, "debug", "native-project-host");
    await mkdir(dirname(implicit), { recursive: true });
    await writeFile(implicit, "");
    await expect(exportNativeBindings(options, directory, implicit)).rejects.toThrow(/another platform/);
    expect(await readFile(output, "utf8")).toBe("export const answer = 7;\n");

    await expect(
      exportHostBindings({ command: join(directory, "missing-host") }, { output }, directory),
    ).rejects.toThrow(/Host executable not found/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 30000);

test("declared native assets and include_str inputs trigger rebuilds while unrelated files do not", async () => {
  const directory = await fixture("solid-project-watch-", { buildScript: true });
  const asset = join(directory, "assets/message.txt");
  const extra = join(directory, "extra/notes.bin");
  try {
    await mkdir(join(directory, "assets"), { recursive: true });
    await mkdir(join(directory, "extra"), { recursive: true });
    await writeFile(asset, "hello\n");
    await writeFile(extra, "notes\n");
    await writeFile(join(directory, "README.md"), "# fixture\n");
    await writeFile(
      join(directory, "build.rs"),
      'fn main() { println!("cargo:rerun-if-changed=assets/message.txt"); }\n',
    );
    await writeFile(
      join(directory, "src/main.rs"),
      `${HOST_SOURCE}\n#[allow(dead_code)]\nconst MESSAGE: &str = include_str!("../assets/message.txt");\n`,
    );
    const options = {
      manifestPath: join(directory, "Cargo.toml"),
      bin: "native-project-host",
      output: join(directory, ".generated/native.ts"),
      watch: ["extra"],
    };
    await exportNativeBindings(options, directory);
    const inputs = await nativeWatchInputs(options, directory, new AbortController().signal);
    expect(inputs.declared).toContain(asset);
    expect(inputs.declared).toContain(join(directory, "src/main.rs"));
    expect(isNativeInput(asset, inputs)).toBe(true);
    expect(isNativeInput(extra, inputs)).toBe(true);
    expect(isNativeInput(join(directory, "src/main.rs"), inputs)).toBe(true);
    // A README or an unrelated file must not restart the native session.
    expect(isNativeInput(join(directory, "README.md"), inputs)).toBe(false);
    expect(isNativeInput(join(directory, "package.json"), inputs)).toBe(false);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("the CLI prepares and checks the same project the plugin uses", async () => {
  const directory = await fixture("solid-project-cli-");
  const bindings = join(directory, ".generated/native.ts");
  const marker = join(directory, "config-resolved.txt");
  const cli = join(repo, "packages/solid-gpui-vite/src/cli.ts");
  const run = (args: readonly string[]) =>
    Bun.spawnSync(["bun", cli, ...args], { cwd: repo, stdout: "pipe", stderr: "pipe" });
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      `import { writeFileSync } from "node:fs";
import { solidGpui } from ${JSON.stringify(plugin)};
const observer = { name: "observer", enforce: "pre", configResolved: () => writeFileSync(${JSON.stringify(marker)}, "resolved") };
export default { root: import.meta.dirname, plugins: [observer, solidGpui({ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } })] };
`,
    );
    const prepared = run(["prepare", "--root", directory, "--json"]);
    expect(prepared.exitCode, prepared.stderr.toString()).toBe(0);
    expect(JSON.parse(prepared.stdout.toString()).native.profileDirectory).toBe("debug");
    expect(run(["prepare", "--check", "--root", directory]).exitCode).toBe(0);
    // Checking reads the same config but never resolves it, so no plugin hook may run.
    expect(await Bun.file(marker).exists()).toBe(false);

    await writeFile(bindings, "export const answer = 0;\n");
    const stale = run(["prepare", "--check", "--root", directory]);
    expect(stale.exitCode).toBe(1);
    expect(stale.stderr.toString()).toContain("stale");
    expect(await readFile(bindings, "utf8")).toBe("export const answer = 0;\n");

    expect(run(["nonsense"]).exitCode).toBe(2);
    expect(run(["--help"]).exitCode).toBe(0);

    // A delegated command keeps its own flag grammar, so unknown flags reach it verbatim.
    const observed = join(directory, "preview-args.json");
    const runtime = join(directory, "preview-runtime.js");
    await mkdir(join(directory, "dist"), { recursive: true });
    await mkdir(join(directory, ".solid-gpui"), { recursive: true });
    await writeFile(join(directory, "dist/app.js"), "// production bundle\n");
    await writeFile(
      runtime,
      `await Bun.write(${JSON.stringify(observed)}, JSON.stringify(Bun.argv.slice(2)));\nprocess.exit(4);\n`,
    );
    await writeFile(
      join(directory, ".solid-gpui/artifacts.json"),
      serializeNativeArtifacts({
        version: 1,
        root: directory,
        runtime: "bun",
        entry: join(directory, "app.js"),
        outDir: join(directory, "dist"),
        tsconfig: join(directory, ".solid-gpui/tsconfig.json"),
        bundle: join(directory, "dist/app.js"),
        host: { command: process.execPath, args: [runtime], output: join(directory, ".generated/native.ts") },
        native: {
          manifestPath: join(directory, "Cargo.toml"),
          bin: "native-project-host",
          features: [],
          profile: "dev",
          profileDirectory: "debug",
          locked: true,
        },
      }),
    );
    const previewed = run(["preview", "--root", directory, "--window", "main", "--other=1"]);
    expect(previewed.exitCode, previewed.stderr.toString()).toBe(4);
    expect(JSON.parse(await readFile(observed, "utf8"))).toEqual(["--window", "main", "--other=1"]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("profile directories and artifact paths are predictable for every profile", () => {
  expect(cargoProfileDirectory()).toBe("debug");
  expect(cargoProfileDirectory("debug")).toBe("debug");
  expect(cargoProfileDirectory("release")).toBe("release");
  expect(cargoProfileDirectory("profiling")).toBe("profiling");
  const artifacts: NativeArtifacts = {
    version: 1,
    root: "/app",
    runtime: "bun",
    entry: "/app/app.js",
    outDir: "/app/dist",
    tsconfig: "/app/.solid-gpui/tsconfig.json",
    native: {
      manifestPath: "/app/Cargo.toml",
      bin: "app",
      features: [],
      profile: "release",
      profileDirectory: "release",
      locked: true,
      targetDirectory: "/app/target",
    },
  };
  expect(expectedExecutablePath(artifacts)).toBe(
    join("/app/target/release", process.platform === "win32" ? "app.exe" : "app"),
  );
  expect(expectedExecutablePath(artifacts, "dev")).toBe(
    join("/app/target/debug", process.platform === "win32" ? "app.exe" : "app"),
  );
  // Only a recorded host is authoritative; a different profile is an expectation.
  expect(recordedHostExecutable(artifacts)).toBeUndefined();
  expect(
    recordedHostExecutable({ ...artifacts, native: { ...artifacts.native!, executable: "/app/target/release/app" } }),
  ).toBe("/app/target/release/app");
  expect(artifactTargetTriple(join("/app/target", "x86_64-unknown-linux-gnu", "debug", "app"), "/app/target")).toBe(
    "x86_64-unknown-linux-gnu",
  );
  expect(artifactTargetTriple("/app/target/debug/app", "/app/target")).toBeUndefined();
  expect(targetRunsOnHost("aarch64-apple-darwin", { architecture: "arm64", platform: "darwin" })).toBe(true);
  expect(targetRunsOnHost("x86_64-apple-darwin", { architecture: "arm64", platform: "darwin" })).toBe(false);
  expect(targetRunsOnHost("x86_64-unknown-linux-gnu", { architecture: "arm64", platform: "darwin" })).toBe(false);
  expect(targetRunsOnHost(undefined)).toBe(true);
  expect(JSON.parse(serializeNativeArtifacts(artifacts)).native.bin).toBe("app");
});

test("the prepared config follows the runtime: QuickJS types and source mappings agree", async () => {
  const directory = await fixture("solid-project-tsconfig-");
  try {
    await mkdir(join(directory, "node_modules/@solid-gpui/core"), { recursive: true });
    await writeFile(
      join(directory, "node_modules/@solid-gpui/core/package.json"),
      '{"name":"@solid-gpui/core","version":"0.0.0"}',
    );
    // The table mirrors the one solidGpuiSource() publishes for its runtime aliases.
    await writeFile(
      join(directory, "vite.config.ts"),
      `import { solidGpui } from ${JSON.stringify(plugin)};
const source = { name: "solid-gpui-source", enforce: "pre", config: () => ({ resolve: { conditions: ["solid-gpui-source"] } }) };
Object.defineProperty(source, Symbol.for("solid-gpui.source.mappings"), { value: { "@solid-gpui/core": ${JSON.stringify(join(directory, "core.ts"))} } });
export default { root: import.meta.dirname, plugins: [solidGpui({ entry: "app.js", runtime: "quickjs", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }), source] };
`,
    );
    const project = await loadProject({ root: directory });
    expect(project.runtime).toBe("quickjs");
    expect(project.bundle).toBe(join(directory, "dist/app.js"));
    expect(project.customConditions).toEqual(["solid-gpui-source"]);
    // An ssr conditions list replaces the root one, so a condition selected for the runtime must
    // survive into the environment that actually runs the application.
    const { resolveConfig } = await import("vite");
    const resolved = await resolveConfig(
      { configFile: join(directory, "vite.config.ts"), root: directory, logLevel: "silent" },
      "build",
    );
    expect(resolved.environments.ssr.resolve.conditions).toContain("solid-gpui-source");
    const prepared = await prepareProject({ root: directory });
    const { compilerOptions } = JSON.parse(await readFile(prepared.project.tsconfig, "utf8"));
    expect(compilerOptions.lib).toEqual(["ES2024"]);
    expect(compilerOptions.types).toEqual(["@solid-gpui/core/quickjs"]);
    expect(compilerOptions.moduleResolution).toBe("bundler");
    expect(compilerOptions.module).toBe("preserve");
    expect(compilerOptions.jsx).toBe("preserve");
    expect(compilerOptions.noEmit).toBe(true);
    expect(compilerOptions.customConditions).toEqual(["solid-gpui-source"]);
    expect(compilerOptions.paths["@solid-gpui/core"]).toEqual([join(directory, "core.ts")]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("a clean target discovers declared inputs after the first build, even outside the crate", async () => {
  const directory = await fixture("solid-project-refresh-", { buildScript: true });
  const crate = join(directory, "native");
  const shared = join(directory, "contract");
  const asset = join(shared, "message.txt");
  try {
    await mkdir(join(crate, "src"), { recursive: true });
    await mkdir(shared, { recursive: true });
    await writeFile(asset, "hello\n");
    await writeFile(
      join(crate, "Cargo.toml"),
      '[package]\nname = "native-project-refresh"\nversion = "0.0.0"\nedition = "2024"\nbuild = "build.rs"\n[workspace]\n[[bin]]\nname = "native-project-host"\npath = "src/main.rs"\n',
    );
    await writeFile(
      join(crate, "Cargo.lock"),
      `${LOCKFILE}\n[[package]]\nname = "native-project-refresh"\nversion = "0.0.0"\n`,
    );
    await writeFile(
      join(crate, "build.rs"),
      'fn main() { println!("cargo:rerun-if-changed=../contract/message.txt"); }\n',
    );
    await writeFile(
      join(crate, "src/main.rs"),
      `${HOST_SOURCE}\n#[allow(dead_code)]\nconst MESSAGE: &str = include_str!("../../contract/message.txt");\n`,
    );
    const options = {
      manifestPath: join(crate, "Cargo.toml"),
      bin: "native-project-host",
      output: join(directory, ".generated/native.ts"),
    };
    // A session may start before anything was ever built: no fingerprints exist yet.
    const clean = await nativeWatchInputs(options, crate, new AbortController().signal);
    expect(clean.fingerprints).toEqual([]);
    expect(clean.declared).toEqual([]);

    await prepareNativeHost(options, crate);
    const refreshed = await refreshNativeWatchInputs(clean);
    // The first build created the fingerprints, and they are rediscovered rather than skipped.
    expect(refreshed.fingerprints.length).toBeGreaterThan(0);
    expect(refreshed.declared).toContain(asset);
    expect(refreshed.declared).toContain(join(crate, "src/main.rs"));
    expect(isNativeInput(asset, refreshed)).toBe(true);
    // A declared file outside every package root needs its own watch entry.
    expect(externalWatchInputs(refreshed)).toContain(asset);
    expect(externalWatchInputs(refreshed)).not.toContain(join(crate, "src/main.rs"));
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("build-script resources are declared even when no dep-info and no include mentions them", async () => {
  const directory = await fixture("solid-project-resources-", { buildScript: true });
  const crate = join(directory, "native");
  const resources = join(directory, "contract/resources");
  const patch = join(resources, "version.patch");
  try {
    await mkdir(join(crate, "src"), { recursive: true });
    await mkdir(resources, { recursive: true });
    await writeFile(patch, "diff\n");
    await writeFile(
      join(crate, "Cargo.toml"),
      '[package]\nname = "native-project-resources"\nversion = "0.0.0"\nedition = "2024"\nbuild = "build.rs"\n[workspace]\n[[bin]]\nname = "native-project-host"\npath = "src/main.rs"\n',
    );
    await writeFile(
      join(crate, "Cargo.lock"),
      `${LOCKFILE}\n[[package]]\nname = "native-project-resources"\nversion = "0.0.0"\n`,
    );
    // The resource is never compiled into the binary, so no dep-info can mention it.
    await writeFile(
      join(crate, "build.rs"),
      'fn main() { println!("cargo:rerun-if-changed=../contract/resources"); }\n',
    );
    await writeFile(join(crate, "src/main.rs"), HOST_SOURCE);
    const options = {
      manifestPath: join(crate, "Cargo.toml"),
      bin: "native-project-host",
      output: join(directory, ".generated/native.ts"),
    };
    await prepareNativeHost(options, crate);
    const inputs = await refreshNativeWatchInputs(
      await nativeWatchInputs(options, crate, new AbortController().signal),
    );
    // Cargo records the declared directory in the build script's fingerprint, not in dep-info.
    expect(inputs.declared).toContain(resources);
    expect(isNativeInput(patch, inputs)).toBe(true);
    expect(isNativeInput(resources, inputs)).toBe(true);
    // The watcher needs the directory itself, not every file inside it.
    const external = externalWatchInputs(inputs);
    expect(external).toContain(resources);
    expect(external).not.toContain(patch);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("the record follows the bundle Vite emits and the plugin dedupes Solid for dist consumers", async () => {
  const directory = await fixture("solid-project-emitted-");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      `import { solidGpui, solidGpuiSource } from ${JSON.stringify(plugin)};
export default {
  root: import.meta.dirname,
  build: { rolldownOptions: { output: { entryFileNames: "app.[hash:8].js" } } },
  plugins: [solidGpui({ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } })],
};
`,
    );
    // Source tooling is reachable from the plugin entry, not only from the /source subpath.
    const { solidGpuiSource: exported } = await import("../packages/solid-gpui-vite/src/index.ts");
    expect(typeof exported).toBe("function");

    const { resolveConfig } = await import("vite");
    const resolved = await resolveConfig(
      { configFile: join(directory, "vite.config.ts"), root: directory, logLevel: "silent" },
      "build",
    );
    // An ordinary dist consumer must share one Solid instance with the SDK.
    expect(resolved.resolve.dedupe).toContain("solid-js");

    await prepareProject({ root: directory });
    const predicted = await readNativeArtifacts(directory);
    // Before the build the name is only a prediction, because Vite owns it.
    expect(predicted?.bundle).toBe(join(directory, "dist/app.[hash:8].js"));

    const { build } = await import("vite");
    await build({ configFile: join(directory, "vite.config.ts"), root: directory, logLevel: "silent" });
    const emitted = await readNativeArtifacts(directory);
    expect(emitted?.bundle).not.toBe(predicted?.bundle);
    expect(await stat(emitted!.bundle!)).toBeTruthy();
    expect(emitted!.bundle!).toMatch(/\/dist\/app\.[0-9a-zA-Z_-]+\.js$/);
    // An unchanged successful build stays previewable: the record is compared on stable identity,
    // not on the concrete hash a pattern produces.
    expect(await previewApplication({ root: directory })).toBe(0);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("prepare builds the configured target, exports the catalog from a runnable exporter, and runs a host override", async () => {
  const directory = await fixture("solid-project-cross-");
  const shim = join(directory, "shim");
  const log = join(directory, "cargo-args.log");
  const exporter = join(directory, "exporter.js");
  const runtime = join(directory, "runtime.js");
  const observation = join(directory, "observation.json");
  const targetDirectory = join(directory, "target");
  const foreign = process.platform === "darwin" ? "x86_64-unknown-linux-gnu" : "aarch64-apple-darwin";
  const executable = join(targetDirectory, foreign, "debug", "native-project-host");
  const previousPath = process.env.PATH;
  try {
    // The foreign toolchain is not available here, so Cargo's two answers are synthesized: the
    // target directory and one artifact message naming the executable it would have produced.
    await mkdir(shim, { recursive: true });
    await writeFile(
      join(shim, "cargo"),
      `#!/usr/bin/env bun
import { appendFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
const args = Bun.argv.slice(2);
appendFileSync(${JSON.stringify(log)}, JSON.stringify(args) + "\\n");
if (args[0] === "metadata") {
  console.log(JSON.stringify({ workspace_root: ${JSON.stringify(directory)}, target_directory: ${JSON.stringify(targetDirectory)}, workspace_default_members: [], packages: [], resolve: { root: null, nodes: [] } }));
} else {
  const executable = join(${JSON.stringify(targetDirectory)}, ${JSON.stringify(foreign)}, "debug", "native-project-host");
  mkdirSync(dirname(executable), { recursive: true });
  writeFileSync(executable, "");
  console.log(JSON.stringify({ reason: "compiler-artifact", target: { kind: ["bin"], name: "native-project-host" }, executable }));
}
`,
    );
    await chmod(join(shim, "cargo"), 0o755);
    await writeFile(
      exporter,
      'if (!Bun.argv.includes("--export-native")) process.exit(9);\nconsole.log("export const answer = 11;");\n',
    );
    await writeFile(
      runtime,
      `await Bun.write(${JSON.stringify(observation)}, JSON.stringify(Bun.argv.slice(2)));\nprocess.exit(5);\n`,
    );
    process.env.PATH = `${shim}:${previousPath}`;
    const native = `{ manifestPath: "Cargo.toml", bin: "native-project-host", target: ${JSON.stringify(foreign)}, exporter: { command: process.execPath, args: [${JSON.stringify(exporter)}] } }`;
    await writeFile(join(directory, "vite.config.ts"), configSource(`{ entry: "app.js", native: ${native} }`));
    const prepared = await prepareProject({ root: directory });
    const invocations: unknown[] = (await readFile(log, "utf8"))
      .trim()
      .split("\n")
      .map((line) => JSON.parse(line) as unknown);
    const built = invocations.find((args) => Array.isArray(args) && args[0] === "build");
    // The configured target is really built, with the same locked default as any other build.
    expect(built).toContain("--target");
    expect(built).toContain(foreign);
    expect(built).toContain("--locked");
    // The catalog comes from the exporter, and the record names the artifact Cargo produced.
    expect(await readFile(join(directory, ".generated/native.ts"), "utf8")).toBe("export const answer = 11;\n");
    expect(prepared.artifacts.native?.executable).toBe(executable);
    expect(prepared.artifacts.native?.target).toBe(foreign);
    expect(prepared.artifacts.host?.command).toBe(executable);
    // Without a runnable host the launcher refuses rather than executing another platform's binary.
    await expect(previewApplication({ root: directory })).rejects.toThrow(/cannot run on this machine/);

    // A host override runs locally while the native build keeps targeting the other platform.
    await mkdir(join(directory, "dist"), { recursive: true });
    await writeFile(join(directory, "dist/app.js"), "// production bundle\n");
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(
        `{ entry: "app.js", native: ${native}, host: { command: process.execPath, args: [${JSON.stringify(runtime)}] } }`,
      ),
    );
    const overridden = await prepareProject({ root: directory });
    expect(overridden.artifacts.host?.command).toBe(process.execPath);
    expect(overridden.artifacts.native?.executable).toBe(executable);
    expect(await previewApplication({ root: directory, args: ["--flag"] })).toBe(5);
    expect(JSON.parse(await readFile(observation, "utf8"))).toEqual(["--flag"]);
  } finally {
    process.env.PATH = previousPath;
    await rm(directory, { recursive: true, force: true });
  }
}, 30000);

test("an unusable artifact record is reported instead of surfacing later", async () => {
  const directory = await fixture("solid-project-record-");
  const record = join(directory, ".solid-gpui/artifacts.json");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(`{ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }`),
    );
    await mkdir(join(directory, ".solid-gpui"), { recursive: true });
    expect(await readNativeArtifacts(directory)).toBeUndefined();
    const usable = {
      version: 1,
      root: directory,
      runtime: "bun",
      entry: join(directory, "app.js"),
      outDir: join(directory, "dist"),
      tsconfig: "x",
    };
    const rejects = async (value: string, pattern: RegExp) => {
      await writeFile(record, value);
      await expect(readNativeArtifacts(directory)).rejects.toThrow(pattern);
    };
    await rejects("{ truncated", /not valid JSON/);
    await rejects(JSON.stringify({ ...usable, version: 2 }), /another tool version/);
    await rejects(JSON.stringify({ ...usable, tsconfig: undefined }), /tsconfig/);
    await rejects(JSON.stringify({ ...usable, outDir: undefined }), /outDir/);
    await rejects(JSON.stringify({ ...usable, runtime: "electron" }), /runtime/);
    await rejects(JSON.stringify({ ...usable, host: { args: [] } }), /no command/);
    await rejects(
      JSON.stringify({ ...usable, native: { manifestPath: "Cargo.toml", profile: "dev" } }),
      /profileDirectory/,
    );
    await rejects(JSON.stringify({ ...usable, root: join(directory, "somewhere-else") }), /records the root/);
    // A corrupt record must fail the launcher too, not silently start something else.
    await expect(previewApplication({ root: directory })).rejects.toThrow(/artifact record/);
    await writeFile(record, JSON.stringify(usable));
    expect((await readNativeArtifacts(directory))?.runtime).toBe("bun");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 30000);

test("an output function that nests the entry stays previewable while a changed output directory does not", async () => {
  const directory = await fixture("solid-project-output-function-");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      `import { solidGpui } from ${JSON.stringify(plugin)};
export default {
  root: import.meta.dirname,
  build: { rolldownOptions: { output: { entryFileNames: () => "assets/main.js" } } },
  plugins: [solidGpui({ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } })],
};
`,
    );
    const { build } = await import("vite");
    await build({ configFile: join(directory, "vite.config.ts"), root: directory, logLevel: "silent" });
    const emitted = await readNativeArtifacts(directory);
    // The entry lands in a nested directory decided by the function; the identity is the outDir.
    expect(emitted?.bundle).toBe(join(directory, "dist/assets/main.js"));
    expect(emitted?.outDir).toBe(join(directory, "dist"));
    expect(await stat(emitted!.bundle!)).toBeTruthy();
    expect(await previewApplication({ root: directory })).toBe(0);

    // The same record against a configuration that writes elsewhere is refused.
    await writeFile(
      join(directory, "vite.config.ts"),
      `import { solidGpui } from ${JSON.stringify(plugin)};
export default {
  root: import.meta.dirname,
  build: { outDir: "build", rolldownOptions: { output: { entryFileNames: () => "assets/main.js" } } },
  plugins: [solidGpui({ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } })],
};
`,
    );
    await expect(previewApplication({ root: directory })).rejects.toThrow(/build output directory/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 60000);

test("preview runs the recorded host against the production bundle, or explains what is missing", async () => {
  const directory = await fixture("solid-project-preview-");
  const observation = join(directory, "observation.json");
  const runtime = join(directory, "runtime.js");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(
        `{ entry: "app.js", runtime: "quickjs", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }`,
      ),
    );
    await writeFile(
      runtime,
      `await Bun.write(${JSON.stringify(observation)}, JSON.stringify({ args: Bun.argv.slice(2), runner: process.env.SOLID_GPUI_VITE_RUNNER ?? null }));\nprocess.exit(7);\n`,
    );
    // Nothing is built yet: preview must name the command that produces the bundle.
    await expect(previewApplication({ root: directory })).rejects.toThrow(/vite build/);

    await mkdir(join(directory, "dist"), { recursive: true });
    await mkdir(join(directory, ".solid-gpui"), { recursive: true });
    await writeFile(join(directory, "dist/app.js"), "// production bundle\n");
    await writeFile(
      join(directory, ".solid-gpui/artifacts.json"),
      serializeNativeArtifacts({
        version: 1,
        root: directory,
        runtime: "quickjs",
        entry: join(directory, "app.js"),
        outDir: join(directory, "dist"),
        tsconfig: join(directory, ".solid-gpui/tsconfig.json"),
        bundle: join(directory, "dist/app.js"),
        host: { command: process.execPath, args: [runtime], output: join(directory, ".generated/native.ts") },
      }),
    );
    // A record for another configuration must not launch an old entry in silence.
    const recorded = await readNativeArtifacts(directory);
    if (!recorded) throw new Error("the fixture should have written an artifact record");
    await writeFile(
      join(directory, ".solid-gpui/artifacts.json"),
      serializeNativeArtifacts({ ...recorded, entry: join(directory, "other-entry.js") }),
    );
    await expect(previewApplication({ root: directory })).rejects.toThrow(/do not match/);

    process.env.SOLID_GPUI_VITE_RUNNER = JSON.stringify(["inherited"]);
    await writeFile(join(directory, ".solid-gpui/artifacts.json"), serializeNativeArtifacts(recorded));
    expect(await previewApplication({ root: directory, args: ["--window", "main"] })).toBe(7);
    delete process.env.SOLID_GPUI_VITE_RUNNER;
    // A QuickJS host must not inherit an enclosing session's Bun runner.
    expect(JSON.parse(await readFile(observation, "utf8"))).toEqual({
      args: ["--runtime", "quickjs", join(directory, "dist/app.js"), "--window", "main"],
      runner: null,
    });
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 30000);

test("preview hands the bundle to the Bun runtime through the host's runner contract", async () => {
  const directory = await fixture("solid-project-preview-bun-");
  const observation = join(directory, "observation.txt");
  const runtime = join(directory, "runtime.js");
  try {
    await writeFile(
      join(directory, "vite.config.ts"),
      configSource(`{ entry: "app.js", native: { manifestPath: "Cargo.toml", bin: "native-project-host" } }`),
    );
    await writeFile(
      runtime,
      `await Bun.write(${JSON.stringify(observation)}, process.env.SOLID_GPUI_VITE_RUNNER ?? "missing");\nprocess.exit(3);\n`,
    );
    await mkdir(join(directory, "dist"), { recursive: true });
    await mkdir(join(directory, ".solid-gpui"), { recursive: true });
    await writeFile(join(directory, "dist/app.js"), "// production bundle\n");
    await writeFile(
      join(directory, ".solid-gpui/artifacts.json"),
      serializeNativeArtifacts({
        version: 1,
        root: directory,
        runtime: "bun",
        entry: join(directory, "app.js"),
        outDir: join(directory, "dist"),
        tsconfig: join(directory, ".solid-gpui/tsconfig.json"),
        bundle: join(directory, "dist/app.js"),
        host: { command: process.execPath, args: [runtime], output: join(directory, ".generated/native.ts") },
      }),
    );
    expect(await previewApplication({ root: directory })).toBe(3);
    expect(JSON.parse(await readFile(observation, "utf8"))).toEqual([
      process.execPath,
      "--conditions=browser",
      join(directory, "dist/app.js"),
    ]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}, 30000);
