export const componentDescriptionsChinese: Record<string, string> = {
  "A retained native carousel with keyboard navigation and pagination.": "保留原生状态的轮播，支持键盘导航与分页。",
  "Native motion samples transitions, springs and keyframes without per-frame JavaScript updates.":
    "原生动画支持过渡、弹簧和关键帧，无需逐帧更新 JavaScript。",
  "Retain children until their native exit animation completes.": "保留子内容，直到原生退出动画完成。",
  "An accessible native control with application-owned visuals.": "由应用定义外观的无障碍原生控件。",
  "Reveal scrollable content with edge fades that disappear at the boundaries.":
    "通过边缘淡出提示可滚动内容，滚动到边界时对应淡出消失。",
  "Show application status and contextual information.": "显示应用状态与上下文信息。",
  "Search and select rows from a grouped collection.": "搜索并选择分组集合中的数据行。",
  "A button for actions, with variants, loading and disabled states.": "用于触发操作的按钮，支持样式、加载和禁用状态。",
  "Group related actions in a single control.": "将相关操作组合为一组按钮。",
  "Reveal related sections without leaving the page.": "展开或收起相关内容。",
  "Display a contextual message and its severity.": "展示提示信息及其重要程度。",
  "Represent people with photos, names or initials.": "用照片、姓名或首字母表示用户。",
  "Attach a count or status indicator to another element.": "为元素添加数量或状态标记。",
  "Show the current location within a hierarchy.": "展示当前页面在层级中的位置。",
  "Connect a boolean control to Solid state.": "将开关状态连接到 Solid 信号。",
  "Choose one option from a group.": "从一组选项中选择一个。",
  "Group toggle buttons for related preferences.": "组合相关的切换按钮。",
  "Copy a value to the system clipboard.": "将内容复制到系统剪贴板。",
  "Show or hide a section of content.": "展开或隐藏一段内容。",
  "Edit text using native selection, keyboard shortcuts and input methods.": "使用原生选区、快捷键和输入法编辑文本。",
  "Edit a number within a range.": "输入指定范围内的数值。",
  "Enter a short verification code.": "输入短验证码。",
  "Select a value along a continuous range.": "通过滑块选择范围内的数值。",
  "Display or change a rating.": "展示或修改评分。",
  "Navigate between pages of results.": "在多页结果之间导航。",
  "Choose from labeled, grouped options.": "从可分组的选项中选择。",
  "Choose a date from a calendar.": "从日历中选择日期。",
  "Choose and edit a color.": "选择并编辑颜色。",
  "Show progress toward completion.": "展示任务完成进度。",
  "Indicate that an operation is in progress.": "表示操作正在进行。",
  "Reserve space while content is loading.": "在内容加载时保留布局空间。",
  "Animate a text label while work is in progress.": "在处理任务时显示动态文字。",
  "Display a label with optional secondary text.": "显示标签及可选的辅助文字。",
  "Render a text value inside component compositions.": "在组合组件中显示文本。",
  "Display selectable rich text or Markdown.": "显示可选择的富文本或 Markdown。",
  "Display an SVG icon from the host asset collection.": "显示宿主资源中的 SVG 图标。",
  "Draw a caret indicator.": "绘制指示符。",
  "Display a keyboard shortcut.": "展示键盘快捷键。",
  "Open a destination from a text label.": "从文字链接打开目标地址。",
  "Separate adjacent content or sections.": "分隔相邻内容或章节。",
  "Present a short category or status label.": "展示简短的分类或状态标签。",
  "Navigate between related views.": "在相关视图之间切换。",
  "Show the current step in a sequence.": "展示流程中的当前步骤。",
  "Compose a table from headers, rows, cells and a caption.": "使用表头、行、单元格和标题组合表格。",
  "Compose file attachments with media, metadata and actions.": "组合附件的媒体预览、信息和操作。",
  "Group conversation bubbles with content and reactions.": "组合消息气泡、内容和回应。",
  "Compose a conversation with avatars, headers and message content.": "使用头像、标题和正文组成会话消息。",
  "Add a compact status marker to a message or activity.": "为消息或动态添加紧凑的状态标记。",
  "Lay out labeled form fields.": "排列带标签的表单字段。",
  "Display labeled values in a structured layout.": "以结构化布局展示带标签的值。",
  "Place related controls in a labeled group.": "将相关控件放入带标题的分组。",
  "Let people resize adjacent panes.": "允许用户调整相邻面板的大小。",
  "Build a navigation sidebar with grouped destinations.": "构建包含分组导航的侧边栏。",
  "Compose the chrome of a native application window.": "组合原生应用窗口的标题栏、状态栏和边框。",
  "Keep content within a bounded, keyboard-accessible region.": "在限定区域中管理内容滚动与键盘焦点。",
  "Compose selectable rows in a scrolling list.": "在可滚动列表中组合可选行。",
  "Render a large collection of native child elements efficiently.": "高效渲染大量原生子元素。",
  "Present a focused dialog with a title, description and actions.": "使用带标题、说明和操作的对话框聚焦当前任务。",
  "Open supporting content in a panel at the window edge.": "在窗口边缘的面板中打开辅助内容。",
  "Deliver a dismissible message inside the application.": "在应用内发送可关闭的通知。",
  "Show contextual information inside the current window. For native content beyond its boundary, see the System popovers guide.":
    "在当前窗口内展示上下文信息。需要越过窗口边界时，请参阅系统弹层指南。",
  "Show contextual information next to a trigger.": "在触发元素旁展示上下文信息。",
  "Explain a control on hover or keyboard focus.": "在悬停或键盘聚焦时说明控件。",
  "Offer related actions in a dropdown menu.": "在下拉菜单中提供相关操作。",
  "Present a menu of contextual actions.": "展示上下文操作菜单。",
  "Open an operating-system menu from a trigger.": "从触发控件打开操作系统菜单。",
  "Provide an application menu bar.": "提供应用菜单栏。",
  "Search and select commands from grouped results.": "搜索并选择分组命令。",
  "Explore nested folders or hierarchical data.": "浏览嵌套文件夹或层级数据。",
  "Display typed rows with column sizing, sorting and selection.": "展示支持列宽、排序和选择的数据表。",
  "Build searchable application preferences with resettable fields.": "构建可搜索、可重置的应用设置。",
  "Arrange persistent workspace panes as tabs or split panels.": "将工作区面板排列为标签页或分割面板。",
  "Visualize a series of labeled values.": "可视化一组带标签的数值。",
  "Compare multiple data series across labeled categories.": "比较多个数据系列在不同类别中的表现。",
  "Compare open, high, low and close values.": "比较开盘、最高、最低和收盘值。",
  "Show how categories contribute to a total.": "展示各类别在总量中的占比。",
  "Visualize flows between connected categories.": "可视化类别之间的流动关系。",
  "Draw custom charts from typed plotting primitives.": "使用绘图基础元素构建自定义图表。",
  "Mark a point in plot coordinates.": "标记绘图坐标中的一个点。",
  "Add a crosshair at a plot position.": "在绘图位置添加十字参考线。",
  "Display labeled values near a plot cursor.": "在绘图光标附近展示带标签的数值。",
};
